const { Sequelize } = require("sequelize");
const { v4 } = require('uuid');
const currencies = [
    { id: v4(), code: "RUB", symbol: "₽", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AFN", symbol: "؋", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "EUR", symbol: "€", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ALL", symbol: "L", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GBP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GGP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "DZD", symbol: "د.ج", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AOA", symbol: "Kz", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "XCD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ARS", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AMD", symbol: "֏", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AWG", symbol: "ƒ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SHP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AUD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AZN", symbol: "₼", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BSD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BHD", symbol: ".د.ب", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BDT", symbol: "৳", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BBD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BYN", symbol: "Br", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BZD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "XOF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BMD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BTN", symbol: "Nu.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "INR", symbol: "₹", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BOB", symbol: "Bs.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "USD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BAM", symbol: "KM", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BWP", symbol: "P", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BRL", symbol: "R$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BND", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SGD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BGN", symbol: "лв.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "BIF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KHR", symbol: "៛", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "XAF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CAD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CVE", symbol: "Esc", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KYD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CLP", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CNY", symbol: "¥", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "COP", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KMF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CDF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CKD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NZD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CRC", symbol: "₡", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "HRK", symbol: "kn", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CUP", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CUC", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ANG", symbol: "ƒ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CZK", symbol: "Kč", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "DKK", symbol: "kr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "DJF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "DOP", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "EGP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ERN", symbol: "Nfk", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SZL", symbol: "L", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ZAR", symbol: "R", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ETB", symbol: "Br", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "FKP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "FOK", symbol: "kr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "FJD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "XPF", symbol: "₣", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GMD", symbol: "D", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GEL", symbol: "₾", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GHS", symbol: "₵", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GIP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GTQ", symbol: "Q", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GNF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "GYD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "HTG", symbol: "G", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "HNL", symbol: "L", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "HKD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "HUF", symbol: "Ft", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ISK", symbol: "kr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "IDR", symbol: "Rp", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "IRR", symbol: "﷼", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "IQD", symbol: "ع.د", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "IMP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "JMD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "JPY", symbol: "¥", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "JEP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "JOD", symbol: "د.ا", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KZT", symbol: "₸", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KES", symbol: "Sh", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KID", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KPW", symbol: "₩", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KRW", symbol: "₩", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KWD", symbol: "د.ك", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "KGS", symbol: "с", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LAK", symbol: "₭", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LBP", symbol: "ل.ل", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LSL", symbol: "L", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LRD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LYD", symbol: "ل.د", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "CHF", symbol: "Fr.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MOP", symbol: "P", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MGA", symbol: "Ar", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MWK", symbol: "MK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MYR", symbol: "RM", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MVR", symbol: ".ރ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MRU", symbol: "UM", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MUR", symbol: "₨", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MXN", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MDL", symbol: "L", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MNT", symbol: "₮", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MAD", symbol: "د.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MZN", symbol: "MT", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MMK", symbol: "Ks", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NAD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NPR", symbol: "रू", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NIO", symbol: "C$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NGN", symbol: "₦", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MKD", symbol: "ден", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TRY", symbol: "₺", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "NOK", symbol: "kr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "OMR", symbol: "ر.ع.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PKR", symbol: "₨", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PAB", symbol: "B/.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PGK", symbol: "K", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PYG", symbol: "₲", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PEN", symbol: "S/.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PHP", symbol: "₱", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PND", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PLN", symbol: "zł", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "QAR", symbol: "ر.ق", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "RON", symbol: "lei", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "RWF", symbol: "Fr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "MAD", symbol: "د. م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "WST", symbol: "T", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "STN", symbol: "Db", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SAR", symbol: "﷼‎", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "RSD", symbol: "дин.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SCR", symbol: "₨", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SLL", symbol: "Le", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SBD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SOS", symbol: "Sh", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SLS", symbol: "Sl", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SSP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "LKR", symbol: "Rs", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SDG", symbol: "ج.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SRD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SEK", symbol: "kr", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "SYP", symbol: "£", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TWD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TJS", symbol: "ЅМ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TZS", symbol: "Sh", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "THB", symbol: "฿", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TOP", symbol: "T$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "PRB", symbol: "р.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TTD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TND", symbol: "د.ت", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TMT", symbol: "m", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "TVD", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "UGX", symbol: "Sh", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "UAH", symbol: "₴", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "AED", symbol: "د.إ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "UYU", symbol: "$", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "UZS", symbol: "сўм", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "VUV", symbol: "Vt", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "VES", symbol: "Bs.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "VND", symbol: "₫", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "YER", symbol: "ر.ي", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), code: "ZMW", symbol: "ZK", createdAt: new Date(), updatedAt: new Date() }
];

const EN = "en";
const AR = "ar";


const localizedCurrencies = [
    { id: v4(), refId: currencies[0].id, language: "en", name: "Russian ruble", standardCode: "RUB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[1].id, language: "en", name: "Afghan afghani", standardCode: "AFN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[2].id, language: "en", name: "Euro", standardCode: "EUR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[3].id, language: "en", name: "Albanian lek", standardCode: "ALL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[4].id, language: "en", name: "British pound", standardCode: "GBP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[5].id, language: "en", name: "Guernsey pound", standardCode: "GGP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[6].id, language: "en", name: "Algerian dinar", standardCode: "DZD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[7].id, language: "en", name: "Angolan kwanza", standardCode: "AOA", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[8].id, language: "en", name: "Eastern Caribbean dollar", standardCode: "XCD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[9].id, language: "en", name: "Argentine peso", standardCode: "ARS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[10].id, language: "en", name: "Armenian dram", standardCode: "AMD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[11].id, language: "en", name: "Aruban florin", standardCode: "AWG", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[12].id, language: "en", name: "Saint Helena pound", standardCode: "SHP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[13].id, language: "en", name: "Australian dollar", standardCode: "AUD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[14].id, language: "en", name: "Azerbaijani manat", standardCode: "AZN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[15].id, language: "en", name: "Bahamian dollar", standardCode: "BSD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[16].id, language: "en", name: "Bahraini dinar", standardCode: "BHD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[17].id, language: "en", name: "Bangladeshi taka", standardCode: "BDT", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[18].id, language: "en", name: "Barbadian dollar", standardCode: "BBD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[19].id, language: "en", name: "Belarusian ruble", standardCode: "BYN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[20].id, language: "en", name: "Belize dollar", standardCode: "BZD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[21].id, language: "en", name: "West African CFA franc", standardCode: "XOF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[22].id, language: "en", name: "Bermudian dollar", standardCode: "BMD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[23].id, language: "en", name: "Bhutanese ngultrum", standardCode: "BTN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[24].id, language: "en", name: "Indian rupee", standardCode: "INR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[25].id, language: "en", name: "Bolivian boliviano", standardCode: "BOB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[26].id, language: "en", name: "United States dollar", standardCode: "USD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[27].id, language: "en", name: "Bosnia and Herzegovina convertible mark", standardCode: "BAM", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[28].id, language: "en", name: "Botswana pula", standardCode: "BWP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[29].id, language: "en", name: "Brazilian real", standardCode: "BRL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[30].id, language: "en", name: "Brunei dollar", standardCode: "BND", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[31].id, language: "en", name: "Singapore dollar", standardCode: "SGD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[32].id, language: "en", name: "Bulgarian lev", standardCode: "BGN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[33].id, language: "en", name: "Burundian franc", standardCode: "BIF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[34].id, language: "en", name: "Cambodian riel", standardCode: "KHR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[35].id, language: "en", name: "Central African CFA franc", standardCode: "XAF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[36].id, language: "en", name: "Canadian dollar", standardCode: "CAD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[37].id, language: "en", name: "Cape Verdean escudo", standardCode: "CVE", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[38].id, language: "en", name: "Cayman Islands dollar", standardCode: "KYD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[39].id, language: "en", name: "Chilean peso", standardCode: "CLP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[40].id, language: "en", name: "Chinese yuan", standardCode: "CNY", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[41].id, language: "en", name: "Colombian peso", standardCode: "COP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[42].id, language: "en", name: "Comorian franc", standardCode: "KMF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[43].id, language: "en", name: "Congolese franc", standardCode: "CDF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[44].id, language: "en", name: "Cook Islands dollar", standardCode: "CKD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[45].id, language: "en", name: "New Zealand dollar", standardCode: "NZD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[46].id, language: "en", name: "Costa Rican colón", standardCode: "CRC", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[47].id, language: "en", name: "Croatian kuna", standardCode: "HRK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[48].id, language: "en", name: "Cuban peso", standardCode: "CUP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[49].id, language: "en", name: "Cuban convertible peso", standardCode: "CUC", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[50].id, language: "en", name: "Netherlands Antillean guilder", standardCode: "ANG", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[51].id, language: "en", name: "Czech koruna", standardCode: "CZK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[52].id, language: "en", name: "Danish krone", standardCode: "DKK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[53].id, language: "en", name: "Djiboutian franc", standardCode: "DJF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[54].id, language: "en", name: "Dominican peso", standardCode: "DOP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[55].id, language: "en", name: "Egyptian pound", standardCode: "EGP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[56].id, language: "en", name: "Eritrean nakfa", standardCode: "ERN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[57].id, language: "en", name: "Swazi lilangeni", standardCode: "SZL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[58].id, language: "en", name: "South African rand", standardCode: "ZAR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[59].id, language: "en", name: "Ethiopian birr", standardCode: "ETB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[60].id, language: "en", name: "Falkland Islands pound", standardCode: "FKP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[61].id, language: "en", name: "Faroese króna", standardCode: "FOK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[62].id, language: "en", name: "Fijian dollar", standardCode: "FJD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[63].id, language: "en", name: "CFP franc", standardCode: "XPF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[64].id, language: "en", name: "Gambian dalasi", standardCode: "GMD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[65].id, language: "en", name: "Georgian lari", standardCode: "GEL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[66].id, language: "en", name: "Ghanaian cedi", standardCode: "GHS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[67].id, language: "en", name: "Gibraltar pound", standardCode: "GIP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[68].id, language: "en", name: "Guatemalan quetzal", standardCode: "GTQ", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[69].id, language: "en", name: "Guinean franc", standardCode: "GNF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[70].id, language: "en", name: "Guyanese dollar", standardCode: "GYD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[71].id, language: "en", name: "Haitian gourde", standardCode: "HTG", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[72].id, language: "en", name: "Honduran lempira", standardCode: "HNL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[73].id, language: "en", name: "Hong Kong dollar", standardCode: "HKD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[74].id, language: "en", name: "Hungarian forint", standardCode: "HUF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[75].id, language: "en", name: "Icelandic króna", standardCode: "ISK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[76].id, language: "en", name: "Indonesian rupiah", standardCode: "IDR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[77].id, language: "en", name: "Iranian rial", standardCode: "IRR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[78].id, language: "en", name: "Iraqi dinar", standardCode: "IQD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[79].id, language: "en", name: "Manx pound", standardCode: "IMP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[80].id, language: "en", name: "Jamaican dollar", standardCode: "JMD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[81].id, language: "en", name: "Japanese yen", standardCode: "JPY", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[82].id, language: "en", name: "Jersey pound", standardCode: "JEP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[83].id, language: "en", name: "Jordanian dinar", standardCode: "JOD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[84].id, language: "en", name: "Kazakhstani tenge", standardCode: "KZT", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[85].id, language: "en", name: "Kenyan shilling", standardCode: "KES", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[86].id, language: "en", name: "Kiribati dollar", standardCode: "KID", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[87].id, language: "en", name: "North Korean won", standardCode: "KPW", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[88].id, language: "en", name: "South Korean won", standardCode: "KRW", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[89].id, language: "en", name: "Kuwaiti dinar", standardCode: "KWD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[90].id, language: "en", name: "Kyrgyzstani som", standardCode: "KGS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[91].id, language: "en", name: "Lao kip", standardCode: "LAK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[92].id, language: "en", name: "Lebanese pound", standardCode: "LBP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[93].id, language: "en", name: "Lesotho loti", standardCode: "LSL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[94].id, language: "en", name: "Liberian dollar", standardCode: "LRD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[95].id, language: "en", name: "Libyan dinar", standardCode: "LYD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[96].id, language: "en", name: "Swiss franc", standardCode: "CHF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[97].id, language: "en", name: "Macanese pataca", standardCode: "MOP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[98].id, language: "en", name: "Malagasy ariary", standardCode: "MGA", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[99].id, language: "en", name: "Malawian kwacha", standardCode: "MWK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[100].id, language: "en", name: "Malaysian ringgit", standardCode: "MYR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[101].id, language: "en", name: "Maldivian rufiyaa", standardCode: "MVR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[102].id, language: "en", name: "Mauritanian ouguiya", standardCode: "MRU", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[103].id, language: "en", name: "Mauritian rupee", standardCode: "MUR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[104].id, language: "en", name: "Mexican peso", standardCode: "MXN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[105].id, language: "en", name: "Moldovan leu", standardCode: "MDL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[106].id, language: "en", name: "Mongolian tögrög", standardCode: "MNT", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[107].id, language: "en", name: "Moroccan dirham", standardCode: "MAD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[108].id, language: "en", name: "Mozambican metical", standardCode: "MZN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[109].id, language: "en", name: "Burmese kyat", standardCode: "MMK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[110].id, language: "en", name: "Namibian dollar", standardCode: "NAD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[111].id, language: "en", name: "Nepalese rupee", standardCode: "NPR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[112].id, language: "en", name: "Nicaraguan córdoba", standardCode: "NIO", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[113].id, language: "en", name: "Nigerian naira", standardCode: "NGN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[114].id, language: "en", name: "Macedonian denar", standardCode: "MKD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[115].id, language: "en", name: "Turkish lira", standardCode: "TRY", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[116].id, language: "en", name: "Norwegian krone", standardCode: "NOK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[117].id, language: "en", name: "Omani rial", standardCode: "OMR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[118].id, language: "en", name: "Pakistani rupee", standardCode: "PKR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[119].id, language: "en", name: "Panamanian balboa", standardCode: "PAB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[120].id, language: "en", name: "Papua New Guinean kina", standardCode: "PGK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[121].id, language: "en", name: "Paraguayan guaraní", standardCode: "PYG", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[122].id, language: "en", name: "Peruvian sol", standardCode: "PEN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[123].id, language: "en", name: "Philippine peso", standardCode: "PHP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[124].id, language: "en", name: "Pitcairn Islands dollar", standardCode: "PND", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[125].id, language: "en", name: "Polish złoty", standardCode: "PLN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[126].id, language: "en", name: "Qatari riyal", standardCode: "QAR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[127].id, language: "en", name: "Romanian leu", standardCode: "RON", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[128].id, language: "en", name: "Rwandan franc", standardCode: "RWF", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[129].id, language: "en", name: "Moroccan dirham", standardCode: "MAD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[130].id, language: "en", name: "Samoan tālā", standardCode: "WST", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[131].id, language: "en", name: "São Tomé and Príncipe dobra", standardCode: "STN", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[132].id, language: "en", name: "Saudi riyal", standardCode: "SAR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[133].id, language: "en", name: "Serbian dinar", standardCode: "RSD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[134].id, language: "en", name: "Seychellois rupee", standardCode: "SCR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[135].id, language: "en", name: "Sierra Leonean leone", standardCode: "SLL", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[136].id, language: "en", name: "Solomon Islands dollar", standardCode: "SBD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[137].id, language: "en", name: "Somali shilling", standardCode: "SOS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[138].id, language: "en", name: "Somaliland shilling", standardCode: "SLS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[139].id, language: "en", name: "South Sudanese pound", standardCode: "SSP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[140].id, language: "en", name: "Sri Lankan rupee", standardCode: "LKR", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[141].id, language: "en", name: "Sudanese pound", standardCode: "SDG", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[142].id, language: "en", name: "Surinamese dollar", standardCode: "SRD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[143].id, language: "en", name: "Swedish krona", standardCode: "SEK", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[144].id, language: "en", name: "Syrian pound", standardCode: "SYP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[145].id, language: "en", name: "New Taiwan dollar", standardCode: "TWD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[146].id, language: "en", name: "Tajikistani somoni", standardCode: "TJS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[147].id, language: "en", name: "Tanzanian shilling", standardCode: "TZS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[148].id, language: "en", name: "Thai baht", standardCode: "THB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[149].id, language: "en", name: "Tongan paʻanga", standardCode: "TOP", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[150].id, language: "en", name: "Transnistrian ruble", standardCode: "PRB", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[151].id, language: "en", name: "Trinidad and Tobago dollar", standardCode: "TTD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[152].id, language: "en", name: "Tunisian dinar", standardCode: "TND", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[153].id, language: "en", name: "Turkmenistan manat", standardCode: "TMT", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[154].id, language: "en", name: "Tuvaluan dollar", standardCode: "TVD", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[155].id, language: "en", name: "Ugandan shilling", standardCode: "UGX", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[156].id, language: "en", name: "Ukrainian hryvnia", standardCode: "UAH", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[157].id, language: "en", name: "United Arab Emirates dirham", standardCode: "AED", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[158].id, language: "en", name: "Uruguayan peso", standardCode: "UYU", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[159].id, language: "en", name: "Uzbekistani soʻm", standardCode: "UZS", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[160].id, language: "en", name: "Vanuatu vatu", standardCode: "VUV", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[161].id, language: "en", name: "Venezuelan bolívar soberano", standardCode: "VES", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[162].id, language: "en", name: "Vietnamese đồng", standardCode: "VND", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[163].id, language: "en", name: "Yemeni rial", standardCode: "YER", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[164].id, language: "en", name: "Zambian kwacha", standardCode: "ZMW", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[0].id, language: "ar", name: "روبل روسي", standardCode: "ر.ر.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[1].id, language: "ar", name: "أفغاني أفغاني", standardCode: "أ.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[2].id, language: "ar", name: "يورو", standardCode: "ي.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[3].id, language: "ar", name: "ليك ألباني", standardCode: "ل.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[4].id, language: "ar", name: "جنيه استرليني", standardCode: "ج.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[5].id, language: "ar", name: "جنيه جيرنزي", standardCode: "ج.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[6].id, language: "ar", name: "دينار جزائري", standardCode: "د.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[7].id, language: "ar", name: "كوانزا أنغولية", standardCode: "ك.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[8].id, language: "ar", name: "دولار شرق كاريبي", standardCode: "د.ش.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[9].id, language: "ar", name: "بيزو أرجنتيني", standardCode: "ب.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[10].id, language: "ar", name: "دراما ارميني", standardCode: "د.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[11].id, language: "ar", name: "أروبا فلورين", standardCode: "أ.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[12].id, language: "ar", name: "جنيه سانت هيلانة", standardCode: "ج.س.ه.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[13].id, language: "ar", name: "دولار استرالي", standardCode: "د.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[14].id, language: "ar", name: "مانات أذربيجان", standardCode: "م.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[15].id, language: "ar", name: "دولار باهاما", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[16].id, language: "ar", name: "دينار بحريني", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[17].id, language: "ar", name: "تاكا بنجلاديشي", standardCode: "ت.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[18].id, language: "ar", name: "دولار بربادوسي", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[19].id, language: "ar", name: "روبل بيلاروسي", standardCode: "ر.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[20].id, language: "ar", name: "دولار بليز", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[21].id, language: "ar", name: "فرنك غرب أفريقي", standardCode: "ف.غ.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[22].id, language: "ar", name: "دولار برمودي", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[23].id, language: "ar", name: "نولترم بوتاني", standardCode: "ن.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[24].id, language: "ar", name: "روبية هندية", standardCode: "ر.ه.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[25].id, language: "ar", name: "بوليفيانو بوليفي", standardCode: "ب.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[26].id, language: "ar", name: "دولار أمريكي", standardCode: "د.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[27].id, language: "ar", name: "مارك البوسنة والهرسك", standardCode: "م.ا.و.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[28].id, language: "ar", name: "بوتسوانا بولا", standardCode: "ب.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[29].id, language: "ar", name: "ريال برازيلي", standardCode: "ر.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[30].id, language: "ar", name: "دولار بروناي", standardCode: "د.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[31].id, language: "ar", name: "دولار سينغافوري", standardCode: "د.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[32].id, language: "ar", name: "ليف بلغاري", standardCode: "ل.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[33].id, language: "ar", name: "فرنك بوروندي", standardCode: "ف.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[34].id, language: "ar", name: "رييل كمبودي", standardCode: "ر.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[35].id, language: "ar", name: "فرنك وسط أفريقيا", standardCode: "ف.و.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[36].id, language: "ar", name: "دولار كندي", standardCode: "د.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[37].id, language: "ar", name: "اسكودو رأس الأخضر", standardCode: "ا.ر.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[38].id, language: "ar", name: "دولار جزر كايمان", standardCode: "د.ج.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[39].id, language: "ar", name: "بيزو تشيلي", standardCode: "ب.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[40].id, language: "ar", name: "يوان صيني", standardCode: "ي.ص.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[41].id, language: "ar", name: "بيزو كولومبي", standardCode: "ب.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[42].id, language: "ar", name: "فرنك جزر القمر", standardCode: "ف.ج.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[43].id, language: "ar", name: "فرنك كونغولي", standardCode: "ف.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[44].id, language: "ar", name: "دولار جزر كوك", standardCode: "د.ج.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[45].id, language: "ar", name: "دولار نيوزيلندي", standardCode: "د.ن.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[46].id, language: "ar", name: "كولون كوستاريكي", standardCode: "ك.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[47].id, language: "ar", name: "كونا كرواتية", standardCode: "ك.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[48].id, language: "ar", name: "بيزو كوبي", standardCode: "ب.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[49].id, language: "ar", name: "بيزو كوبي", standardCode: "ب.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[50].id, language: "ar", name: "جلدر جزر الأنتيل الهولندية", standardCode: "ج.ج.ا.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[51].id, language: "ar", name: "كورونا تشيكية", standardCode: "ك.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[52].id, language: "ar", name: "كرونة دنماركية", standardCode: "ك.د.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[53].id, language: "ar", name: "فرنك جيبوتي", standardCode: "ف.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[54].id, language: "ar", name: "بيزو دومينيكي", standardCode: "ب.د.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[55].id, language: "ar", name: "جنيه مصري", standardCode: "ج.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[56].id, language: "ar", name: "نكفة إريترية", standardCode: "ن.إ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[57].id, language: "ar", name: "ليلانجيني سوازي", standardCode: "ل.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[58].id, language: "ar", name: "راند جنوب أفريقيا", standardCode: "ر.ج.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[59].id, language: "ar", name: "بر اثيوبي", standardCode: "ب.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[60].id, language: "ar", name: "جنيه جزر فوكلاند", standardCode: "ج.ج.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[61].id, language: "ar", name: "كرونا فارو", standardCode: "ك.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[62].id, language: "ar", name: "دولار فيجي", standardCode: "د.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[63].id, language: "ar", name: "فرنك سي إف بي", standardCode: "ف.س.إ.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[64].id, language: "ar", name: "دالاسي جامبي", standardCode: "د.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[65].id, language: "ar", name: "لاري جورجي", standardCode: "ل.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[66].id, language: "ar", name: "سيدي الغاني", standardCode: "س.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[67].id, language: "ar", name: "جنيه جبل طارق", standardCode: "ج.ج.ط.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[68].id, language: "ar", name: "كتزال غواتيمالا", standardCode: "ك.غ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[69].id, language: "ar", name: "فرنك غينيا", standardCode: "ف.غ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[70].id, language: "ar", name: "دولار جوياني", standardCode: "د.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[71].id, language: "ar", name: "غورد هايتي", standardCode: "غ.ه.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[72].id, language: "ar", name: "لمبيرا هندوراسي", standardCode: "ل.ه.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[73].id, language: "ar", name: "دولار هونج كونج", standardCode: "د.ه.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[74].id, language: "ar", name: "فورنت مجري", standardCode: "ف.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[75].id, language: "ar", name: "كرونا آيسلندية", standardCode: "ك.آ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[76].id, language: "ar", name: "روبية اندونيسية", standardCode: "ر.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[77].id, language: "ar", name: "ريال إيراني", standardCode: "ر.إ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[78].id, language: "ar", name: "دينار عراقي", standardCode: "د.ع.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[79].id, language: "ar", name: "مانكس الجنيه", standardCode: "م.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[80].id, language: "ar", name: "دولار جامايكي", standardCode: "د.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[81].id, language: "ar", name: "ين ياباني", standardCode: "ي.ي.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[82].id, language: "ar", name: "جنيه جيرسي", standardCode: "ج.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[83].id, language: "ar", name: "دينار أردني", standardCode: "د.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[84].id, language: "ar", name: "تنغي كازاخستاني", standardCode: "ت.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[85].id, language: "ar", name: "شلن كيني", standardCode: "ش.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[86].id, language: "ar", name: "دولار كيريباتي", standardCode: "د.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[87].id, language: "ar", name: "وون كوريا شمالية", standardCode: "و.ك.ش.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[88].id, language: "ar", name: "وون كوريا جنوبية", standardCode: "و.ك.ج.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[89].id, language: "ar", name: "دينار كويتي", standardCode: "د.ك.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[90].id, language: "ar", name: "سوم قرغيزستاني", standardCode: "س.ق.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[91].id, language: "ar", name: "كيب لاو", standardCode: "ك.ل.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[92].id, language: "ar", name: "ليرة لبنانية", standardCode: "ل.ل.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[93].id, language: "ar", name: "لوتي ليسوتو", standardCode: "ل.ل.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[94].id, language: "ar", name: "دولار ليبيري", standardCode: "د.ل.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[95].id, language: "ar", name: "دينار ليبي", standardCode: "د.ل.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[96].id, language: "ar", name: "فرنك سويسري", standardCode: "ف.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[97].id, language: "ar", name: "باتاكا ماكاوي", standardCode: "ب.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[98].id, language: "ar", name: "ارياري مدغشقر", standardCode: "ا.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[99].id, language: "ar", name: "كواتشا مالاوى", standardCode: "ك.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[100].id, language: "ar", name: "رينغيت ماليزي", standardCode: "ر.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[101].id, language: "ar", name: "روفية جزر المالديف", standardCode: "ر.ج.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[102].id, language: "ar", name: "أوقية موريتانية", standardCode: "أ.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[103].id, language: "ar", name: "روبية موريشيوسية", standardCode: "ر.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[104].id, language: "ar", name: "بيزو مكسيكي", standardCode: "ب.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[105].id, language: "ar", name: "ليو مولدوفا", standardCode: "ل.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[106].id, language: "ar", name: "tögrög المنغولية", standardCode: "t.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[107].id, language: "ar", name: "درهم مغربي", standardCode: "د.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[108].id, language: "ar", name: "متكال موزمبيقي", standardCode: "م.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[109].id, language: "ar", name: "كيات بورمي", standardCode: "ك.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[110].id, language: "ar", name: "دولار ناميبي", standardCode: "د.ن.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[111].id, language: "ar", name: "روبية نيبالية", standardCode: "ر.ن.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[112].id, language: "ar", name: "نيكاراغوا قرطبة", standardCode: "ن.ق.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[113].id, language: "ar", name: "نيرة نيجيرية", standardCode: "ن.ن.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[114].id, language: "ar", name: "دينار مقدوني", standardCode: "د.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[115].id, language: "ar", name: "ليرة تركية", standardCode: "ل.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[116].id, language: "ar", name: "كرونة نرويجية", standardCode: "ك.ن.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[117].id, language: "ar", name: "ريال عماني", standardCode: "ر.ع.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[118].id, language: "ar", name: "روبية باكستانية", standardCode: "ر.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[119].id, language: "ar", name: "بالبوا بنمي", standardCode: "ب.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[120].id, language: "ar", name: "كينا بابوا غينيا الجديدة", standardCode: "ك.ب.غ.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[121].id, language: "ar", name: "غواراني باراغواي", standardCode: "غ.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[122].id, language: "ar", name: "سول بيروفي", standardCode: "س.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[123].id, language: "ar", name: "بيزو فلبيني", standardCode: "ب.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[124].id, language: "ar", name: "دولار جزر بيتكيرن", standardCode: "د.ج.ب.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[125].id, language: "ar", name: "الزلوتي البولندي", standardCode: "ا.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[126].id, language: "ar", name: "ريال قطري", standardCode: "ر.ق.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[127].id, language: "ar", name: "ليو روماني", standardCode: "ل.ر.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[128].id, language: "ar", name: "فرنك رواندي", standardCode: "ف.ر.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[129].id, language: "ar", name: "درهم مغربي", standardCode: "د.م.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[130].id, language: "ar", name: "ساموان تالا", standardCode: "س.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[131].id, language: "ar", name: "ساو تومي وبرينسيبي دوبرا", standardCode: "س.ت.و.د.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[132].id, language: "ar", name: "ريال سعودي", standardCode: "ر.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[133].id, language: "ar", name: "دينار صربي", standardCode: "د.ص.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[134].id, language: "ar", name: "روبية سيشيلية", standardCode: "ر.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[135].id, language: "ar", name: "ليون سيراليوني", standardCode: "ل.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[136].id, language: "ar", name: "دولار جزر سليمان", standardCode: "د.ج.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[137].id, language: "ar", name: "شلن صومالي", standardCode: "ش.ص.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[138].id, language: "ar", name: "شلن صوماليلاند", standardCode: "ش.ص.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[139].id, language: "ar", name: "جنيه جنوب السودان", standardCode: "ج.ج.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[140].id, language: "ar", name: "روبية سريلانكية", standardCode: "ر.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[141].id, language: "ar", name: "جنيه سوداني", standardCode: "ج.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[142].id, language: "ar", name: "دولار سورينامي", standardCode: "د.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[143].id, language: "ar", name: "كرونة سويدية", standardCode: "ك.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[144].id, language: "ar", name: "ليرة سورية", standardCode: "ل.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[145].id, language: "ar", name: "دولار تايواني", standardCode: "د.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[146].id, language: "ar", name: "طاجيكستان سوموني", standardCode: "ط.س.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[147].id, language: "ar", name: "شلن تنزاني", standardCode: "ش.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[148].id, language: "ar", name: "بات تايلندي", standardCode: "ب.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[149].id, language: "ar", name: "بانجا تونجا", standardCode: "ب.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[150].id, language: "ar", name: "روبل ترانسنيستريا", standardCode: "ر.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[151].id, language: "ar", name: "دولار ترينيداد وتوباغو", standardCode: "د.ت.و.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[152].id, language: "ar", name: "دينار تونسي", standardCode: "د.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[153].id, language: "ar", name: "مانات تركمانستان", standardCode: "م.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[154].id, language: "ar", name: "دولار توفالو", standardCode: "د.ت.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[155].id, language: "ar", name: "شلن أوغندي", standardCode: "ش.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[156].id, language: "ar", name: "هريفنيا الأوكرانية", standardCode: "ه.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[157].id, language: "ar", name: "درهم إماراتي", standardCode: "د.إ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[158].id, language: "ar", name: "بيزو أوروغواي", standardCode: "ب.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[159].id, language: "ar", name: "سوم أوزبكستان", standardCode: "س.أ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[160].id, language: "ar", name: "فانواتو فاتو", standardCode: "ف.ف.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[161].id, language: "ar", name: "بوليفار سوبيرانو الفنزويلي", standardCode: "ب.س.ا.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[162].id, language: "ar", name: "الفيتنامية đồng", standardCode: "ا.đ.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[163].id, language: "ar", name: "ريال يمني", standardCode: "ر.ي.", createdAt: new Date(), updatedAt: new Date() },
    { id: v4(), refId: currencies[164].id, language: "ar", name: "كواشا زامبيا", standardCode: "ك.ز.", createdAt: new Date(), updatedAt: new Date() },
]

async function up(queryInterface) {
    await queryInterface.createTable("currencies", {
        id: {
            type: Sequelize.UUID,
            allowNull: false,
            primaryKey: true,
            defaultValue: Sequelize.UUIDV4,
        },
        code: {
            type: new Sequelize.STRING(10),
            allowNull: false,
        },
        symbol: {
            type: new Sequelize.STRING(10),
            allowNull: false,
        },
        createdAt: {
            type: Sequelize.DATE,
            allowNull: false,
        },
        updatedAt: {
            type: Sequelize.DATE,
            allowNull: false,
        },
    });

    await queryInterface.bulkInsert('currencies', currencies);

    await queryInterface.createTable("localized_currencies", {
        id: {
            type: Sequelize.UUID,
            allowNull: false,
            primaryKey: true,
            defaultValue: Sequelize.UUIDV4,
        },
        name: {
            type: Sequelize.STRING,
            allowNull: false,
        },
        standardCode: {
            type: Sequelize.STRING,
            allowNull: false,
        },
        language: {
            type: Sequelize.STRING,
            allowNull: false,
        },
        refId: {
            type: Sequelize.UUID,
            allowNull: false,
        },
        createdAt: {
            type: Sequelize.DATE,
            allowNull: false,
        },
        updatedAt: {
            type: Sequelize.DATE,
            allowNull: false,
        },
    });

    await queryInterface.bulkInsert('localized_currencies', localizedCurrencies);

}

async function down(queryInterface) {
    await queryInterface.dropTable("localized_currencies");
    await queryInterface.dropTable("currencies");
}

module.exports = { up, down };
