export enum ListingStatus {
  Draft,
  Published,
}

/// this for type safe. after add any error to i18n files , you should add it here also 
export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  A_USER_WITH_THIS_EMAIL_ADDRESS_ALREADY_EXISTS = 'A_USER_WITH_THIS_EMAIL_ADDRESS_ALREADY_EXISTS',
  INVALID_OR_EXPIRED_LINK = 'INVALID_OR_EXPIRED_LINK',
  INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE',
  YOU_MUST_ENTER_OLD_PASSWORD = 'YOU_MUST_ENTER_OLD_PASSWORD',
  INVALID_OLD_PASSWORD = 'INVALID_OLD_PASSWORD',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
}