export const listings = [
  {
    id: 1,

    pageType: 'Product',
    ownerId: 1,

    listingTypeId: 1,
    privacy: 'Public',
    media:
      '[{"url":"http://ec2-100-24-21-2.compute-1.amazonaws.com/api/v1/files/product/image/5f33fdb4-18bc-4c60-a48b-bbd02c7ac9c1.350215","bucket":"product","type":"image","fileName":"5f33fdb4-18bc-4c60-a48b-bbd02c7ac9c1.350215"}]',
    name: 'mugs',
    brandName: 'youssef mugs',
    description: 'Good mugs\nGood mugs',
    stockAvailability: 'In Stock',
    advantages: 'Good mugs\nGood mugs',
    uses: 'Good mugs\nGood mugs',
    credentials: '',
    url: 'https://m.facebook.com/',
    priceTypeId: 1,
    price: 100,
    currencyId: 1,
    hiringTypeId: 1,
    offerPrice: 40,
    offerDescription: '',
    socialLinks: '["https://m.facebook.com/","",""]',
    viewsCount: 0,
    status: 1,
    isEdited: false,
    otherHiring: null,
    otherPriceType: '',
    overallRating: 2.3333333333333335,
    totalRatingCount: 3,
  },
  {
    id: 2,
    pageType: 'Skill',
    ownerId: 1,

    listingTypeId: 1,
    privacy: 'Public',
    media:
      '[{"url":"http://ec2-100-24-21-2.compute-1.amazonaws.com/api/v1/files/product/image/f39d1b8e-5703-40ec-845b-8ac13f0af0bc.jpg","bucket":"product","type":"image","fileName":"f39d1b8e-5703-40ec-845b-8ac13f0af0bc.jpg"}]',
    name: 'testtttttttttttt',
    brandName: 'testtttttttttt',
    description: 'testttttttttttttttttttttt',
    stockAvailability: 'In Stock',
    advantages: 'testttttttttttttttttttttt',
    uses: 'testttttttttttttttttttttt',
    credentials: 'testttttttttttttttttttttt',
    url: 'https://test.com',
    priceTypeId: 1,
    price: 120,
    currencyId: 1,
    hiringTypeId: 1,
    offerPrice: 100,
    offerDescription: 'testttttttttttttttttttttt',
    socialLinks:
      '["https://facebook.com","https://Walmart.com","https://xing.com"]',
    viewsCount: 0,
    status: 2,
    isEdited: true,
    otherHiring: null,
    otherPriceType: null,
    overallRating: 0,
    totalRatingCount: 0,
  },
  {
    id: 3,
    pageType: 'Product',
    ownerId: 1,

    listingTypeId: 1,
    privacy: 'Public',
    media:
      '[{"url":"http://ec2-100-24-21-2.compute-1.amazonaws.com/api/v1/files/users/photo/889858a1-72f3-4151-b3bb-c26b244d471b.973648","bucket":"product","type":"image","fileName":"5f33fdb4-18bc-4c60-a48b-bbd02c7ac9c1.350215"}]',
    name: 'Gray Mugs',
    brandName: 'Mohamed mugs',
    description: 'Good flutter\nGood flutter',
    stockAvailability: 'In Stock',
    advantages: 'Good flutter\nGood flutter',
    uses: 'Good flutter\nGood flutter',
    credentials: '',
    url: 'https://m.facebook.com/',
    priceTypeId: 1,
    price: 70,
    currencyId: 1,
    hiringTypeId: 1,
    offerPrice: 50,
    offerDescription: '',
    socialLinks: '["https://m.facebook.com/","",""]',
    viewsCount: 0,
    status: 1,
    isEdited: false,
    otherHiring: null,
    otherPriceType: '',
    overallRating: 4.5,
    totalRatingCount: 2,
  },
];
