name: Imaginative CI/CD

on:
  push:
    branches:
      - dev-new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install -g @nestjs/cli
      - run: npm install
      - run: npm run build

      - name: Copy folder content to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "~/backend-new/dist"
          rm : true
          strip_components: 10
    env:
      CI: true

  after-deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/backend-new
            git checkout dev-new
            npm install 
            pm2 stop new-imaginative-backend
            NODE_ENV=production pm2 start dist/src/main.js --name "new-imaginative-backend"
