name: Imaginative CI/CD

on:
  push:
    branches: 
      - dev-new

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run:  npm install -g @nestjs/cli
    - run: npm install 
    - run: npm run build
    - run: pwd
    - run: ls
    
    env: 
      CI : true


  copy-build-folder-to-server :
   needs: [build]

   runs-on: ubuntu-latest
   steps:
   - uses: appleboy/scp-action@master
     with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      port: ${{ secrets.SSH_PORT }}
      key: ${{ secrets.SSH_KEY }}
      source: "/home/runner/work/backend/backend/dist/"
      target: "~/backend-new/dist"


  deploy:
    needs: [copy-build-folder-to-server]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/backend-new
          git checkout dev-new
          git pull
          npm install 
          pm2 stop new-imaginative-backend
          npm run build
          NODE_ENV=production pm2 start dist/src/main.js --name "new-imaginative-backend"